// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY TypedAnimatorCodeGenerator. DO NOT CHANGE IT.
// </auto-generated>

using UnityEngine;

namespace EgoParadise.Generated
{
    class AnimatorCodeGenConfigureAsset
    {
        public readonly Animator animator = null;
        public readonly int NewFloatId = Animator.StringToHash("New Float");
        public readonly int NewIntId = Animator.StringToHash("New Int");
        public readonly int NewBoolId = Animator.StringToHash("New Bool");
        public readonly int NewTriggerId = Animator.StringToHash("New Trigger");

        public AnimatorCodeGenConfigureAsset(Animator animator)
        {
            this.animator = animator;
        }

        public float GetNewFloat() => this.animator.GetFloat(this.NewFloatId);
        public int GetNewInt() => this.animator.GetInteger(this.NewIntId);
        public bool GetNewBool() => this.animator.GetBool(this.NewBoolId);

        public void SetNewFloat(float NewFloat) => this.animator.SetFloat(this.NewFloatId, NewFloat);
        public void SetNewInt(int NewInt) => this.animator.SetInteger(this.NewIntId, NewInt);
        public void SetNewBool(bool NewBool) => this.animator.SetBool(this.NewBoolId, NewBool);
        public void SetNewTrigger() => this.animator.SetTrigger(this.NewTriggerId);

        public void ResetNewTrigger() => this.animator.ResetTrigger(this.NewTriggerId);
    }
}
